**Introducción a RStudio**
Antes de escribir nuestro primer código, necesitamos un lugar donde ejecutarl. Para esto necesitamos instalar R (https://cran.r-project.org/) y RStudio(https://posit.co/download/rstudio-desktop)

In [ ]:
# ¿Dónde estoy trabajando?
getwd()

In [ ]:
# Establecer el entorno de trabajo

setwd("C:/Curso_Rstudio/")

# Recuerda que para  establecer el directorio de trabajo debe de estar entre comillas ""
# y la ruta debe tener slash o barra inclinada (/)

In [21]:
# Crear  carpetas de salida
dir.create("resultados", showWarnings = FALSE)
dir.create("figuras", showWarnings = FALSE)

In [24]:
# Instalar paquetes
 install.packages <- c(
  "tidyverse",   # manipulación de gráficos
  "janitor",     # tablas limpias
  "skimr",       # resumen rápido de datos
  "gtsummary",   # tablas clínicas
  "broom",       # ordenar salidas de modelos / pruebas
  "readr"        # leer archivos csv
 )

In [ ]:
# Cargar paquetes

# Lista de paquetes a cargar
packages_to_load <- c("tidyverse", "skimr", "gtsummary", "broom", "readr")

# Verificar e instalar/cargar paquetes si es necesario
for (pkg in packages_to_load) {
  if (!require(pkg, character.only = TRUE)) {
    message(paste("Installing package:", pkg))
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  } else {
    message(paste("Package", pkg, "is already loaded or available."))
  }
}

 **Buenas prácticas**


 - No trabajar desde la consola solamente.
 - Guardar instrucciones en scripts.
 - Usar nombres claros: datos_limpios, tabla_1, grafico_glucosa.
 - No usar espacios ni acentos en nombres de objetos.
 - Comentar el razonamiento clínico, no solo el código.

**Variables y tipos de datos**
Las variables son como cajas etiquetadas donde guardamos información para utilizarla despues, ejemplo

In [ ]:
edad = 25
glucosa <- 126
sexo <- "Femenino"
diabetes <- TRUE
nombre = "Christian"
es_estudiante = TRUE

edad
glucosa
sexo
diabetes
nombre
es_estudiante

print(class(edad))
print(class(nombre))
print(class(es_estudiante))

#Operadores aritméticos y relacionales
Los operadoes son las herramientas básicas para hacer las operaciones. Los aritméticos(+, -, *, /) se pueden usar para sumar, restar, multiplicar, promedior, etc. Pero no son los unicos tambien estan los operadores racionales (<, >, =), los cuales nos permiten sabes si los resultadso son iguales o un número es mayor que otro.

In [ ]:
a = 10
b = 3

print(a + b)
print(a ** 2)       # Potencia
print(a %% b)       # Módulo  Se utiliza para determinar si un número es par o impar
print(a > b)

**Vectores**

En esatdistica rara vez trabajamos con un solo número. Normalmente tenemos muchos números: los resultados de 100 analisís de glucosa, las alturas de 50 personas, etc. Un vector es precisamente eso: una colección ordenada de números.
Con los vectores podemos calcular el promedio, el máximo, el mínimo o la suma de todos los valores de una sola vez.

In [ ]:
edades <- c(23, 25, 19, 34, 28)
glucosas <- c(89, 110, 145, 98, 180)

edades
mean(edades)
median(edades)
sd(edades)
range(edades)

**Comparaciones lógicas**

In [ ]:
glucosas > 126
sum(glucosas > 126)
mean(glucosas > 126)

# Interpretación:
# sum() cuenta cuántos cumplen la condición.
# mean() calcula la proporción TRUE si TRUE=1 y FALSE=0.

**Data frames: tabla de pacientes**

En la vida real, los datos casi nunca vienen como vectores aislados. Normalmente tenemos una tabla donde cada fila es una observación (por ejemplo, un estudiante) y cada columna es una variable (nombre, edad, nota). Esto es exactamente un Data Frame. Aprender a manejar data frames es fundamental porque la mayoría de los problemas de estadística involucran datos organizados de esta forma.

*   Elemento de la lista
*   Elemento de la lista

In [15]:
datos <- data.frame(
    Nombre = c("Ana", "Luis", "María", "José"),
    Edad = c(22, 25, 20, 28),
    Nota = c(9.2, 8.5, 7.8, 9.0)
)
print(datos)


#Ejemplo 2
edades <- c(23, 25, 19, 34, 28)
glucosas <- c(89, 110, 145, 98, 180)

pacientes <- data.frame(
  id = 1:5,
  edad = edades,
  sexo = c("F", "M", "F", "M", "F"),
  glucosa = glucosas,
  diabetes = glucosas >= 126
)

pacientes
summary(pacientes)

  Nombre Edad Nota
1    Ana   22  9.2
2   Luis   25  8.5
3  María   20  7.8
4   José   28  9.0

  id edad sexo glucosa diabetes
1 1  23   F     89     FALSE
2 2  25   M    110     FALSE
3 3  19   F    145      TRUE
4 4  34   M     98     FALSE
5 5  28   F    180      TRUE

       id         edad             sexo      glucosa       diabetes
 Min.   :1   Min.   :19.0   Length   :5   Min.   : 89.0   Mode :logical
 1st Qu.:2   1st Qu.:23.0   N.unique :2   1st Qu.: 98.0   FALSE:3
 Median :3   Median :25.0   N.blank  :0   Median :110.0   TRUE :2
 Mean   :3   Mean   :25.8   Min.nchar:1   Mean   :124.4
 3rd Qu.:4   3rd Qu.:28.0   Max.nchar:1   3rd Qu.:145.0
 Max.   :5   Max.   :34.0                 Max.   :180.0

**Factores**

In [16]:
pacientes$sexo <- factor(pacientes$sexo, levels = c("F", "M"))
pacientes$diabetes <- factor(
  pacientes$diabetes,
  levels = c(FALSE, TRUE),
  labels = c("No", "Sí")
)


pacientes
str(pacientes)
summary(pacientes)

  id edad sexo glucosa diabetes
1 1  23   F     89     No
2 2  25   M    110     No
3 3  19   F    145     Sí
4 4  34   M     98     No
5 5  28   F    180     Sí

'data.frame':	5 obs. of  5 variables:
 $ id      : int  1 2 3 4 5
 $ edad    : num  23 25 19 34 28
 $ sexo    : Factor w/ 2 levels "F","M": 1 2 1 2 1
 $ glucosa : num  89 110 145 98 180
 $ diabetes: Factor w/ 2 levels "No","Sí": 1 1 2 1 2

       id         edad      sexo     glucosa      diabetes
 Min.   :1   Min.   :19.0   F:3   Min.   : 89.0   No:3
 1st Qu.:2   1st Qu.:23.0   M:2   1st Qu.: 98.0   Sí:2
 Median :3   Median :25.0         Median :110.0
 Mean   :3   Mean   :25.8         Mean   :124.4
 3rd Qu.:4   3rd Qu.:28.0         3rd Qu.:145.0
 Max.   :5   Max.   :34.0         Max.   :180.0

**Seleccionar columnas y filas con base R**

In [17]:
pacientes$edad
pacientes[1, ]
pacientes[, "glucosa"]
pacientes[pacientes$glucosa >= 126, ]

[1] 23 25 19 34 28

  id edad sexo glucosa diabetes
1 1  23   F    89      No

[1]  89 110 145  98 180

  id edad sexo glucosa diabetes
3 3  19   F    145     Sí
5 5  28   F    180     Sí

# **Errores comunes**
R distingue mayúsculas/minúsculas:
Edad no es igual a edad.

Los textos van entre comillas:


El operador de asignación recomendado en R es <-

In [19]:
diagnostico <- "Hipertensión"